Adding reference to "sqlite-net-pcl" as there was an error thrown on startup that was being caught by the new logging.
Consolidating the packages that are bought as part of this to the version that was previously used

System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.batteries_v2' or one of its dependencies. The system cannot find the file specified.
File name: 'SQLitePCLRaw.batteries_v2'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)